<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>advent_of_code_25</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Update="InputFiles\input-1">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-1-test">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-2-test">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-2">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-3-test">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-3">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-4-test">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-4">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-8-test">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-8">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-9">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-9-test">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-9-test-2">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="InputFiles\input-9-test-3">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
